# ~/.starship/starship
add_newline = true
#
format="""
[┌────](green) $directory$git_branch$jobs$time
[└](green)$character
"""


[character]
success_symbol = "[>](green)"  # nf-fa-angle_double_right
error_symbol = "[>](red)"  # nf-fa-ban
# vicmd_symbol = "[](bold #ffaa00)"  # nf-fa-angle_double_left

[cmd_duration]
style = "8"
show_milliseconds = true
min_time = 30_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style)"

[directory]
truncation_length = 1
style = "white"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = " [$branch]($style) "
style = "yellow"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = ""
style = "bold dimmed #9fe820"
disabled = true

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
show_percentage = true
show_swap = true
threshold = 50
style = "bold bright white"
disabled = true

[python]
symbol = " "
style = "yellow"
format = "[$symbol$version]($style) "
pyenv_version_name = true
disabled = true

[rust]
symbol = "️ " 
style = "bold #fca103"
format = "[$symbol$version]($style) "
disabled = true

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = true

[username]
style_user = "blue"
format = "[$user]($style) "
